### ISSUE TITLE
pushImage failing

### ISSUE THREAD

**Issue by nvx** [jfrog/jenkins-artifactory-plugin#268] opened 2020-03-31 01:41 UTC
Since updating Jenkins and plugins, I'm getting this stack trace which looks to be guava related on the dockerPush step.

Jenkins 2.222.1, Artifactory Plugin 3.6.1

```
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to cibuild-slave-02
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils.pushImage(DockerAgentUtils.java:129)
		at org.jfrog.hudson.pipeline.common.executors.DockerExecutor.execute(DockerExecutor.java:70)
		at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.run(DockerPushStep.java:104)
		at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.run(DockerPushStep.java:71)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:359)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V
	at com.google.common.io.BaseEncoding$Alphabet.<init>(BaseEncoding.java:458)
	at com.google.common.io.BaseEncoding$Base64Encoding.<init>(BaseEncoding.java:919)
	at com.google.common.io.BaseEncoding.<clinit>(BaseEncoding.java:322)
	at com.github.dockerjava.core.exec.AbstrDockerCmdExec.registryAuth(AbstrDockerCmdExec.java:45)
	at com.github.dockerjava.core.exec.AbstrDockerCmdExec.resourceWithAuthConfig(AbstrDockerCmdExec.java:77)
	at com.github.dockerjava.core.exec.PushImageCmdExec.execute0(PushImageCmdExec.java:39)
	at com.github.dockerjava.core.exec.PushImageCmdExec.execute0(PushImageCmdExec.java:16)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.execute(AbstrAsyncDockerCmdExec.java:56)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:12)
	at com.github.dockerjava.core.command.AbstrAsyncDockerCmd.exec(AbstrAsyncDockerCmd.java:21)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerUtils.pushImage(DockerUtils.java:64)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:137)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:129)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
Caused: java.io.IOException: Remote call on cibuild-slave-02 failed
	at hudson.remoting.Channel.call(Channel.java:1004)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils.pushImage(DockerAgentUtils.java:129)
	at org.jfrog.hudson.pipeline.common.executors.DockerExecutor.execute(DockerExecutor.java:70)
	at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.run(DockerPushStep.java:104)
	at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.run(DockerPushStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:359)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nvx** [comment] 2020-03-31 01:47
After some trial and error, it looks like downgrading "OWASP Markup Formatter" from 2.0 to 1.8 works around the issue.

It looks like 1.8 does not use guava, while 2.0 bundles guava 27.1 which is conflicting perhaps?

**Comment by glevy** [comment] 2020-04-02 13:36
I can confirm both, issue an workaround.

**Comment by Heldain** [comment] 2020-05-28 10:59
I also can confirm both. Will issue be fixed?

**Comment by glevy** [comment] 2020-07-12 04:58
Hi Guys,

Are you handling this?
This issue prevents us from updating other plugins that depend on the OWASP plugin.

Thanks,
Gilad

**Comment by grailsweb** [comment] 2020-07-19 21:55
I also having the same issue.


```
java.lang.NoClassDefFoundError: Could not initialize class com.google.common.io.BaseEncoding
	at com.github.dockerjava.core.exec.AbstrDockerCmdExec.registryAuth(AbstrDockerCmdExec.java:45)
	at com.github.dockerjava.core.exec.AbstrDockerCmdExec.resourceWithAuthConfig(AbstrDockerCmdExec.java:77)
	at com.github.dockerjava.core.exec.PushImageCmdExec.execute0(PushImageCmdExec.java:39)
	at com.github.dockerjava.core.exec.PushImageCmdExec.execute0(PushImageCmdExec.java:16)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.execute(AbstrAsyncDockerCmdExec.java:56)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:12)
	at com.github.dockerjava.core.command.AbstrAsyncDockerCmd.exec(AbstrAsyncDockerCmd.java:21)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerUtils.pushImage(DockerUtils.java:65)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:137)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:129)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils.pushImage(DockerAgentUtils.java:129)
	at org.jfrog.hudson.pipeline.common.executors.DockerExecutor.execute(DockerExecutor.java:70)
	at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.run(DockerPushStep.java:92)
	at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.run(DockerPushStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Or-Gabay** [comment] 2020-07-30 07:08
It seems we have jar conflicts between the Artifactory plugin & the OWASP plugin.
Since version 2.0, the OWASP Plugin started bundling guava 27.1 as one of its dependencies, As a result, the Artifactory Plugin fails with this exception when attempting to push a docker image.
It looks like the docker-java library used by the plugin throws an exception while trying to use the guava.

It seems that issue of conflicting dependencies in Jenkins is something that plugin maintainers have been dealing with for many years now. We have been trying to resolve this conflict. However, after numerous attempts to resolve this issue by making changes to the guava versions used by the Artifactory and OWASP Plugins, which haven’t resolved the issue, we finally decided on taking a completely new approach towards resolving this problem.

Here’s what we are planning to do:
The Jenkins Artifactory Plugin relies on a few build-info dependencies - all of which can be seen the plugin’s pom file - https://github.com/jfrog/jenkins-artifactory-plugin/blob/master/pom.xml
Notice the build-info-extractor-npm dependency for example. It bundles most of the code responsible for invoking the npm CLI commands execution. The Jenkins Artifactory Plugin code actually runs the code in build-info-extractor-npm in a new java process. We did this initially to allow using the Artifactory NPM pipeline APIs together with the Jenkins Docker Plugin. Not because of a dependencies conflict, but in order to allow running the NPM APIs inside a docker container, which is what the docker plugin requires.

So we can take the same approach and create a new build-info-extractor-docker dependency, which its code will run in a different java process, thus eliminating the class loading issues inside the Jenkins JVM. We intend to treat this as a high priority dev task. We’ll update this GitHub issue as we progress towards launching this change.

Till this change becomes available, this issue can be worked around by downgrading the OWASP Plugin to version 1.8.
We would appreciate everyone’s feedback/help with this.

**Comment by Or-Gabay** [comment] 2020-08-18 13:17
We have just release Jenkins Artifactory plugin 3.8.0 which includes the [fix](https://github.com/jfrog/jenkins-artifactory-plugin/issues/268#issuecomment-666174333) I mentioned.
Feel free to upgrade and share your feedback.

**Comment by mgriffin13** [comment] 2020-08-24 15:15
thank you, this should solve my problem.

**Comment by eyalbe4** [comment] 2020-08-24 15:37
Sure @mgriffin13!
Please let us know if all works for you.

**Closed** 2020-09-30 12:30 UTC

**Comment by Or-Gabay** [comment] 2020-10-01 08:14
@mgriffin13, I would like to share with you a [snapshot](https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.8.x-SNAPSHOT/artifactory-3.8.x-20200930.144732-9.hpi) that takes care of creating the temp dir in the same location where Docker Extractor is. This way the temp dir should have access to execute binaries for the docker push command.
I will appreciate your feedback on that!.

**Comment by eyalbe4** [comment] 2020-10-01 08:29
@mgriffin13,
Adding to @Or-Gabay's comment above, with this snapshot version, you no longer need to set the ```java.io.tmpdir``` system property.

**Comment by mgriffin13** [comment] 2020-10-01 13:25
That's great. Thank you. I have not been able to update the Artifactory plugin on my production instance yet, but I was planning on doing it (with the javaArgs parameter) later this month. I'll test the snapshot on my test instance and wait for the final release before updating my production instance.

**Comment by mgriffin13** [comment] 2020-10-21 18:07
@Or-Gabay When is this change going to be formally released?

**Comment by eyalbe4** [comment] 2020-10-21 18:11
@mgriffin13,
This is planned to be included as part of the upcoming release, planned to be published by the end of next week, but possibly sooner.
