### ISSUE TITLE
Conan: Error in retry upload leads to `currentBuild.result` set to  `FAILURE`, which always break the job

### ISSUE THREAD

**Issue by climblinne** [jfrog/jenkins-artifactory-plugin#133] opened 2019-04-15 11:38 UTC
This ticket is linked to https://github.com/conan-io/conan/issues/4907

I got the problem, that Conan fails, because he got an error '500', when uploading a package.
Unluckily Conan is (at the moment) not retrying the task, as I put him on the commandline arguments.

So I wrote the following groovy script for Jenkins Pipeline:
```groovy
        // Upload to Conan (Artifactory)
        // It happens sometimes, that 2 processes try to change the same value at the same moment. Therefor we repeat the step.
        def max_retry_upload = 5
        for (i = 0; i <max_retry_upload; i++) {
            try {
                client.run command: "upload * --all --force --retry 5 --retry-wait 10 -r ${name} --confirm".toString(), buildInfo: buildInfo
                break
            }
            catch(Exception e) {
                if (i == max_retry_upload - 1) {
                    println "Current Build result: ${currentBuild.result}"
                    println "Error: Unable to upload, sthrow exception..."
                    throw e
                }
                else {
                    println "Current Build result: ${currentBuild.result} (Change status back to SUCCESS)"
                    println "Warning: Unable to upload, sleep & retry..."
                    currentBuild.result = 'SUCCESS'
                    sleep(5 + 5 * Math.random()) // Wait 5 to 10 seconds
                }
            }
        }
```

The script is working, so that Jenkins build the job (also when the first upload fails). But unluckily he still recognize the first error in the upload as error of the complete job. I thought, when I catch the error, he should ignore the failure. The "currentBuild.result" is already set to "FAILURE" instead of "SUCCESS".
Could it be, that the Artifactory plugin first catch the error, then set "currentBuild.result" to "FAILURE" and then rethrow the execption?

**Comment by climblinne** [comment] 2019-06-06 20:13
Now with Conan 1.6.0 the basic problem is solved, but still another error occurs. See https://github.com/conan-io/conan/issues/5307.

It would be nice, when the plugin would not set `currentBuild.result` itself to `FAILURE`.

**Comment by tmwa** [comment] 2019-07-05 16:19
The plugin should never call `build.setResult(Result.FAILURE)`, as this makes it virtually impossible for a Jenkins job to recover from a conan command error. It is not for the plugin to decide that one build step constitutes a job failure.

**Comment by jgsogo** [comment] 2019-07-26 11:37
@tmwa, having a look at the sources I see that it is a common pattern for all the clients, not just Conan, so probably it won't be changed. If the output is not shown, there is an issue here (https://github.com/conan-io/conan/issues/3962) I need to investigate further.

About your issue, @climblinne, the problem is in the plugin itself. As you say, the first time it fails, the build is marked as a FAILURE and there is nothing you can do about it (check [source here](https://github.com/jfrog/jenkins-artifactory-plugin/blob/master/src/main/java/org/jfrog/hudson/pipeline/common/Utils.java#L264))... now that the issue https://github.com/conan-io/conan/issues/4907 has been fixed, I think that this should no longer be an issue, right?

Thanks!

**Comment by climblinne** [comment] 2019-07-29 12:40
@jsogo As in https://github.com/conan-io/conan/issues/5307 I got another problem after the fix of 4907. May be it would be fine, if we have an extra flag to let the artifactory plugin just not to write the `currentbuild.result`?

**Comment by jgsogo** [comment] 2019-07-29 15:11
Hi, @climblinne . I've opened an issue in the Conan repo (https://github.com/conan-io/conan/issues/5553) to gather CI scenarios, so we can design the set of commands and arguments needed by the plugin. I think it is very interesting to step back and have a look at the full picture.

**Comment by tmwa** [comment] 2019-08-05 12:11
> having a look at the sources I see that it is a common pattern for all the clients, not just Conan, so probably it won't be changed

I noticed this as well. However, I think it should be removed from all clients as the behaviour is wrong for the above reasons.

**Comment by climblinne** [comment] 2019-08-27 06:56
I still got the problem. Could anyone from JFrog have a look inside?

**Comment by climblinne** [comment] 2019-08-27 11:08
I wrote now a ticket in the JFrog issue tracker:
https://www.jfrog.com/jira/browse/HAP-1229

**Closed** 2019-09-05 07:52 UTC

**Comment by yahavi** [comment] 2019-09-08 06:02
@climblinne, @tmwa
Jenkins Artifactory plugin v3.4.0 is out.
This version eliminates `build.setResult(Result.FAILURE)` from the Conan command.
Feel free to upgrade.
