### ISSUE TITLE
v3.11.1 - 500 error from Artifactory when setting build retention (regression from v3.11.0)

### ISSUE THREAD

**Issue by fraz3alpha** [jfrog/jenkins-artifactory-plugin#488] opened 2021-05-26 16:52 UTC
**Describe the bug**

v3.11.0 does not exhibit this issue, but v3.11.1 does (released this week) .

Enabling "Discard old builds from Artifactory..." and the sub item "Discard build artifacts" on a job results in a 500 response from Artifactory when it gets to that point in the job:

```
java.io.IOException: JFrog service failed. Received 500: {
  "errors" : [ {
    "status" : 500,
    "message" : "An unexpected error has occurred, please check Artifactory logs for further details."
  } ]
}
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.throwException(JFrogService.java:54)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.handleUnsuccessfulResponse(JFrogService.java:112)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:135)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.sendBuildRetention(ArtifactoryManager.java:223)
	at org.jfrog.build.extractor.retention.Utils.sendRetentionIfNeeded(Utils.java:50)
	at org.jfrog.build.extractor.retention.Utils.sendBuildAndBuildRetention(Utils.java:72)
	at org.jfrog.build.extractor.retention.Utils.sendBuildAndBuildRetention(Utils.java:75)
	at org.jfrog.hudson.generic.GenericBuildInfoDeployer.deploy(GenericBuildInfoDeployer.java:64)
	at org.jfrog.hudson.generic.ArtifactoryGenericConfigurator$1.tearDown(ArtifactoryGenericConfigurator.java:423)
	at hudson.model.AbstractBuild$AbstractBuildExecution.tearDownBuildEnvironments(AbstractBuild.java:553)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:517)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

The  

**To Reproduce**

- Create a freestyle Jenkins job
- Set a build retention for the job.
- Enable "Discard old builds from Artifactory (requires Artifactory Pro)" and the sub-option "Discard build artifacts"
  ![Screenshot 2021-05-26 at 17 44 42](https://user-images.githubusercontent.com/2786011/119699440-1559dc00-be4a-11eb-8ccf-65b297821900.png)

- Note: You will need a server configured in the main configuration page.

**Expected behavior**

The Jenkins job should complete without errors, and potentially delete some builds in Artifactory. It does not.

**Screenshots**

![Screenshot 2021-05-26 at 17 50 49](https://user-images.githubusercontent.com/2786011/119700367-07588b00-be4b-11eb-97e8-1cd85188ca80.png)

**Versions**
- Jenkins Artifactory plugin version: 3.11.1
- Jenkins operating system: Docker (Ubuntu based) v2.277.2
- Artifactory Version: 7.12.8

**Additional context**

The exception in the Artifactory service logs is:
```
2021-05-26T12:03:26.728Z [jfrt ] [ERROR] [f549c574fbbaae31] [c.e.m.GlobalExceptionMapper:48] [tp-nio-8081-exec-134] -
com.thoughtworks.xstream.io.StreamException:
    at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:73)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
    at com.thoughtworks.xstream.io.xml.StaxReader.<init>(StaxReader.java:45)
    at com.thoughtworks.xstream.io.xml.StaxDriver.createStaxReader(StaxDriver.java:173)
    at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:92)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1338)
    at org.artifactory.rest.common.provider.XStreamAliasProvider.readFrom(XStreamAliasProvider.java:75)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
    at org.artifactory.request.gzip.GZIPReaderInterceptor.aroundReadFrom(GZIPReaderInterceptor.java:33)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
    at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:73)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
    at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
    at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
    at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:271)
    at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:97)
    at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:80)
    at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:74)
    at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:92)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:133)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.artifactory.webapp.servlet.RepoFilter.execute(RepoFilter.java:201)
    at org.artifactory.webapp.servlet.RepoFilter.doFilter(RepoFilter.java:103)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.artifactory.webapp.servlet.authentication.ArtifactoryAuthenticationFilterChain.lambda$doFilter$1(ArtifactoryAuthenticationFilterChain.java:145)
    at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:178)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.artifactory.webapp.servlet.authentication.ArtifactoryBasicAuthenticationFilter.doFilter(ArtifactoryBasicAuthenticationFilter.java:102)
    at org.artifactory.webapp.servlet.authentication.ArtifactoryAuthenticationFilterChain.doFilter(ArtifactoryAuthenticationFilterChain.java:183)
    at org.artifactory.webapp.servlet.AccessFilter.authenticateAndExecute(AccessFilter.java:400)
    at org.artifactory.webapp.servlet.AccessFilter.doFilterInternal(AccessFilter.java:258)
    at org.artifactory.webapp.servlet.AccessFilter.doFilter(AccessFilter.java:201)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.artifactory.webapp.servlet.RequestFilter.doFilter(RequestFilter.java:82)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.artifactory.webapp.servlet.ArtifactoryCsrfFilter.doFilter(ArtifactoryCsrfFilter.java:96)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:164)
    at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
    at org.artifactory.webapp.servlet.SessionFilter.doFilter(SessionFilter.java:68)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.artifactory.webapp.servlet.ArtifactoryTracingFilter.doFilter(ArtifactoryTracingFilter.java:32)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.artifactory.webapp.servlet.ArtifactoryFilter.doFilter(ArtifactoryFilter.java:137)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
    at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:305)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
    at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:701)
    at com.ctc.wstx.sr.BasicStreamReader.handleEOF(BasicStreamReader.java:2229)
    at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2135)
    at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180)
    at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:58)
    ... 93 common frames omitted
```
There is no further information in the request log apart from a 500 return code being returned to the caller.

**Comment by mbartosi** [comment] 2021-05-27 04:40
Same here, Jenkins pipeline:

Deploying build info to: /api/build

Build successfully deployed. Browse it in Artifactory under https://artifacts.xxxxxxxxxxxxxxx

Sending request for build retention, deleting build artifacts, max number of builds to store: 6.

JFrog service failed. Received 500: {

  "errors" : [ {

    "status" : 500,

    "message" : "An unexpected error has occurred, please check Artifactory logs for further details."

  } ]

}

**Comment by dgutzmann** [comment] 2021-05-28 17:03
Looks to also be there in 3.11.2 FYI...

**Comment by catholic-indulgence-vaper** [comment] 2021-05-28 23:13
Same story for plugin version 3.11.2 + Artifactory 7.19.4.
500 from Artifactory side.

**Comment by eyalbe4** [comment] 2021-05-29 03:33
Thank you all for reporting this issue!
Version 3.11.3 of the Artifactory Plugin includes a fix for this issue.
We apologise for the inconvenience caused by this.
Looking forward to your feedback for the fix.

**Comment by Enrice** [comment] 2021-05-31 09:23
is this maybe a duplicate of https://www.jfrog.com/jira/browse/HAP-1464?

**Comment by eyalbe4** [comment] 2021-05-31 10:38
It is a duplicate @Enrice.
Please let us know if the upgrade resolves the issue for you.

**Comment by Enrice** [comment] 2021-05-31 11:54
working in 3.11.3

**Comment by eyalbe4** [comment] 2021-05-31 12:29
Thyanks for the feedback @Enrice!

**Closed by eyalbe4** 2021-05-31 12:29 UTC
Labels: bug

**Comment by fraz3alpha** [comment] 2021-06-01 08:59
@eyalbe4 - Just tested 3.11.3 in a test Jenkins, and it has fixed the server dropdown entries being blank, and the 500 error - from the code changes it looks like these were both related. Thanks for fixing this 👍

**Comment by eyalbe4** [comment] 2021-06-01 10:43
Thank you for the feedback @fraz3alpha!
