### ISSUE TITLE
Artifactory addInteractivePromotion ERROR

### ISSUE THREAD

**Issue by 15846363412** [jfrog/jenkins-artifactory-plugin#395] opened 2020-12-18 07:49 UTC
![image](https://user-images.githubusercontent.com/34851956/102587973-a617e780-4147-11eb-86c6-1c7698885c98.png)

Product automatic promotion no problem, manual promotion error 
Artifactory.addInteractivePromotion server: server, promotionConfig: promotionConfig ,displayName: "Promote me please"
After updating the jenkins version, we found a problem

**Comment by yahavi** [comment] 2020-12-18 09:23
@15846363412,
Thanks for reporting this issue! 
The root cause of this issue is the changes introduced by [Jenkins 2.264](https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/#configuration-ui-tables-to-divs).

We fix this issue in #383. The fix will be included in the next release.

Here's a snapshot version which includes the fix:
https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.10.x-SNAPSHOT/artifactory-3.10.x-20201206.160529-3.hpi


We'd appreciate your feedback on that.

(Duplicates: https://github.com/jfrog/jenkins-artifactory-plugin/issues/381)

**Comment by yahavi** [comment] 2020-12-29 09:25
@15846363412.
We fixed this issue in Jenkins Artifactory plugin 3.10.1. Feel free to upgrade.
We'd appreciate your feedback on that.

**Closed by yahavi** 2020-12-29 09:25 UTC

**Comment by 15846363412** [comment] 2020-12-29 09:42
@yahavi Thanks very much. I updated it just now.
